In [1]:
# Import Necesary Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
players = pd.read_csv('./Data/player_predictions.csv')
goalkeepers = pd.read_csv('./Data/goalkeeper_predictions.csv')
roles = pd.read_csv('./Data/player_role_clusters.csv')

In [2]:
players.head()

,id,name,age,nationality,height,weight,team,league,season,minutes_played,...,shots_score,assists_score,tackles_score,duels_score,dribbles_score,passes_score,foul_score,goalsave_score,discipline_score,rating_pred
0,3581239250,J. Bamba,29.0,Côte d'Ivoire,175 cm,72 kg,Celta Vigo,La Liga,2024,815.0,...,5.043507,5.677778,5.225227,6.015555,5.961304,5.423689,4.816327,NaN,5.795855,4.146636
1,2607061911,Lucas Rosa,25.0,Brazil,176 cm,68 kg,Valladolid,La Liga,2024,1890.0,...,3.711096,5.093275,6.419223,5.031707,4.659863,4.501674,5.112277,NaN,4.904101,6.381719
2,206332792,Abdulay Bah,19.0,Sierra Leone,195 cm,80 kg,Valladolid,La Liga,2024,865.0,...,4.631408,4.582773,5.860307,6.298043,5.894595,4.914884,5.304324,NaN,5.435525,4.487604
3,796815709,A. Tuhami,30.0,Morocco,173 cm,69 kg,Valladolid,La Liga,2024,960.0,...,7.276587,4.688973,6.077299,6.444289,5.204735,4.103764,3.595215,NaN,6.295302,5.835314
4,3804650568,M. Sylla,31.0,Senegal,184 cm,84 kg,Valladolid,La Liga,2024,913.0,...,6.087062,6.532798,4.034882,6.114779,5.628070,4.714168,5.112914,NaN,6.040124,5.746298

In [3]:
goalkeepers.head()

,id,name,age,nationality,height,weight,team,league,season,minutes_played,...,shots_score,assists_score,tackles_score,duels_score,dribbles_score,passes_score,foul_score,goalsave_score,discipline_score,rating_pred
0,3209365995,Rui Silva,31.0,Portugal,191 cm,91 kg,Real Betis,La Liga,2024,1350.0,...,NaN,NaN,3.485820,5.351168,3.444550,4.266232,6.061057,7.743441,4.996894,3.968532
1,3686317755,K. Hein,23.0,Estonia,193 cm,86 kg,Valladolid,La Liga,2024,1980.0,...,NaN,NaN,2.776685,5.072059,2.687174,3.952624,6.933616,8.282296,3.118377,4.654086
2,428742163,G. Mamardashvili,25.0,Georgia,197 cm,90 kg,Valencia,La Liga,2024,1440.0,...,NaN,NaN,3.485820,4.937455,3.444550,4.305737,6.067002,7.526761,4.513833,3.940861
3,2432118490,Sivera,29.0,Spain,184 cm,75 kg,Alaves,La Liga,2024,1584.0,...,NaN,NaN,3.800740,5.278706,3.444550,4.111070,5.638038,7.598683,5.122042,3.962932
4,1467762063,Joan García,24.0,Spain,191 cm,79 kg,Espanyol,La Liga,2024,1980.0,...,NaN,NaN,2.776685,4.696456,2.687174,3.433845,6.551092,8.755708,3.667169,4.782378